### ISSUE TITLE
Backslide / Remark.js PDF rendering issue

### ISSUE THREAD

**Issue by sinedied** [astefanutti/decktape#109]
I'm trying to export this example Remark.js slideshow: https://sinedied.github.io/backslide/

While everything was working as expected with `1.0.0` version of Decktape, the new version has a strange behavior with this slideshow:

- when exporting screenshots, it works properly:
![index_1_1280x720](https://user-images.githubusercontent.com/593151/30099228-68677d10-92e5-11e7-8255-6309a8a9ed73.png)

- when exporting PDF the layout is a complete garbage:
![image](https://user-images.githubusercontent.com/593151/30099243-7bd381c8-92e5-11e7-9b70-50963a1f690b.png)
[index.pdf](https://github.com/astefanutti/decktape/files/1280173/index.pdf)

Is there anything I'm missing?

**Comment by astefanutti** [comment]
I suspect an issue with the Chrome screen media emulation that seems to only affect RemarkJS based presentations. I managed to work-around it with:
https://github.com/astefanutti/decktape/blob/656704c9c6cd992231f0cfc2217e321e3e99f618/plugins/remark.js#L19-L32
But that doesn't seem to be working for Backslide. Would there be any particular CSS rules defined by Backslide?

**Comment by sinedied** [comment]
Those the only print-specific additional rules:
```css
@page {
  // 908px 681px for 4/3 slides
  size: 1210px 681px;
  margin: 0;
}

@media print {
  .remark-slide-scaler {
    width: 100% !important;
    height: 100% !important;
    transform: scale(1) !important;
    top: 0 !important;
    left: 0 !important;
  }
}
```
