### ISSUE TITLE
Linear-gradient background does not work

### ISSUE THREAD

**Issue by Cisneiros** [astefanutti/decktape#61]
I've been struggling to export my Remark presentation. My slides have backgrounds using CSS3 Linear Gradients, and these appear not to work with decktape. This is the CSS I use for the slides:

``` css
.remark-slide-content.blue {
    background: #7474BF;
    background: -webkit-linear-gradient(-30deg, #7474BF, #348AC7);
    background: linear-gradient(-30deg, #7474BF , #348AC7);
    color: #fdfdfd;
}
```

All my slides are exported with white background. If I remove the linear gradient (both with and without `-webkit` prefix), it works (I get the solid BG color as specified). If I leave the gradient (I've tried leaving only the prefixed one, the not prefixed one, and both), I get a white background.

On a side note (and possibly another bug, but I don't want to get into it right now, it just helps eliminate some things on this issue), PhantomJS seems to render linear gradients. My slides used to have `animate.css` fade-in transitions. When I have these on, my slides are exported as raster images (bitmaps) inside the PDF, instead of text. In this case, I get the linear background just fine (but my slides are now images instead of texts). When I remove the animations, I get regular text inside the PDF, but no background.

I'm pretty lost, I must say!
